version: "3.7"

services:
  spautofy:
    build: .
    image: spautofy:latest
    ports:
      - 8080:8080
      - 9090:9090
    env_file: ./.env
    environment:
      DATABASE_URL: postgres://spautofy:spautofy@postgres:5432/spautofy?sslmode=disable
      BASE_URL: http://localhost:8080
      METRICS_PORT: 9090
      PORT: 8080
      SESSION_STORE_KEY: spautofy

  postgres:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: spautofy
      POSTGRES_PASSWORD: spautofy
      POSTGRES_USER: spautofy

  postgres.init:
    image: migrate/migrate:v4.11.0
    entrypoint:
      - wait-for
      - postgres:5432
      - --
      - /run-migrations.sh
    environment:
      DATABASE_URL: postgres://spautofy:spautofy@postgres:5432/spautofy?sslmode=disable
    volumes:
      - ./bin/wait-for:/usr/local/bin/wait-for
      - ./databases/postgres/migrations:/migrations
      - ./databases/postgres/run-migrations.sh:/run-migrations.sh
