version: "3.7"

services:
  spautofy:
    build: .
    image: spautofy:latest
    ports:
      - 8080:8080
    env_file: ./.env
    environment:
      HOSTNAME: localhost:8080
      PORT: 8080
      POSTGRES_DB: spautofy
      POSTGRES_HOST: postgres:5432
      POSTGRES_PASSWORD: spautofy
      POSTGRES_USER: spautofy
      SESSION_STORE_KEY: spautofy

  postgres:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: spautofy
      POSTGRES_PASSWORD: spautofy
      POSTGRES_USER: spautofy

  postgres.init:
    image: migrate/migrate:v4.11.0
    entrypoint:
      - wait-for
      - postgres:5432
      - --
      - /postgres/run-migrations.sh
    environment:
      MIGRATIONS_DIR: /postgres/migrations
      POSTGRES_DB: spautofy
      POSTGRES_HOST: postgres:5432
      POSTGRES_PASSWORD: spautofy
      POSTGRES_USER: spautofy
    volumes:
      - ./bin/wait-for:/usr/local/bin/wait-for
      - ./databases/postgres:/postgres
