CREATE TABLE IF NOT EXISTS schedules (
  id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  spec TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
)
